apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: image-registry-secret
      containers:
      - name: backend
        image: floriankamaj/my-portfolio-app:backend-ebeb84c
        resources:
          limits:
          memory: "64Mi"
          cpu: "100m"
        requests:
          memory: "32Mi"
          cpu: "50m"
        env:
        - name: MONGO_URI
          value: "mongodb://mongodb-service:27017/portfolio"
        - name: RABBITMQ_URL
          value: "amqp://guest:guest@rabbitmq-service:5672"
        ports:
        - containerPort: 5000
---
# k8s/backend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80     
      targetPort: 5000