apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      imagePullSecrets:
        - name: image-registry-secret
      containers:
      - name: worker
        image: floriankamaj/my-portfolio-app:worker-e754ed9
        resources:
          limits:
          memory: "64Mi"
          cpu: "100m"
        requests:
          memory: "32Mi"
          cpu: "50m"
        env:
        - name: RABBITMQ_URL
          value: "amqp://guest:guest@rabbitmq-service:5672"
        - name: SENDGRID_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: SENDGRID_API_KEY
        - name: MY_EMAIL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: MY_EMAIL
        - name: TWILIO_ACCOUNT_SID
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: TWILIO_ACCOUNT_SID
        - name: TWILIO_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: TWILIO_AUTH_TOKEN
        - name: TWILIO_WHATSAPP_NUMBER
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: TWILIO_WHATSAPP_NUMBER
        - name: MY_WHATSAPP_NUMBER
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: MY_WHATSAPP_NUMBER
