name: CI/CD Pipeline

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Run Tests
        env:
          MONGO_URI: mongodb://localhost:27017/testdb
        run: |
          cd backend
          pip install -r requirements.txt
          nosetests --with-color
          
  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set commit hash
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and Push Backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-portfolio-app:backend-${{ steps.vars.outputs.sha_short }} ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/my-portfolio-app:backend-${{ steps.vars.outputs.sha_short }}
          
      - name: Build and Push Worker
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-portfolio-app:worker-${{ steps.vars.outputs.sha_short }} ./notification-microservice
          docker push ${{ secrets.DOCKER_USERNAME }}/my-portfolio-app:worker-${{ steps.vars.outputs.sha_short }}

      - name: Build and Push Frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-portfolio-app:frontend-${{ steps.vars.outputs.sha_short }} ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/my-portfolio-app:frontend-${{ steps.vars.outputs.sha_short }}